---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  notify: Restart nginx

- name: Ensure Nginx service is enabled and running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy custom index.html to Nginx default site
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
